spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: ${POSTGRES_USER:rikkei}
    password: ${POSTGRES_PASSWORD:rikkei}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:rikkeiacademy}

app:
  jwt:
    secret: "${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}"
    access-token-expiration: 900000 # 15 mins
    refresh-token-expiration: 604800000 # 7 days

logging:
  pattern:
    correlation: "[%X{correlationId:-}] "

server:
  port: 8080
